config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  resources :dishes




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def new
    @dish = dish.new(name:"Bandeja paisa",price:"15000",origin:"Antioquia")
  end
  def create
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
  end
  def create
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/new.html.erb
<div class="container">
  <%= form_for @dish  do |f| %>
  <%# <%= form_for(:user, url: dishes_path) do |f| %>
    <div class="form-group">
      <label for="name">Name dish</label>
      <input type="text" name="dish[name]" id="name" class="form-control">
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="origin">Origin</label>
      <input type="text" name="dish[origin]" value="<%= @dish.origin %>" id="origin" class="form-control">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <a class="navbar-brand" href="<%= root_path %>">FoodBook</a>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<%= new_dish_path %>" data-method="get">Create Dish</a></li>
            </ul>
           </div>
        </nav>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>FoodBook!!!!!!</h1>